language: python
python:
  - '3.4'
  - '2.7'
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install inkscape dia asciidoc
  - wget -c https://github.com/downloads/houqp/asciidoc-deckjs/deckjs-1.6.2.zip
  - sudo pip3 install -r requirements.txt
  - virtualenv -p /usr/bin/python2.7 --distribute temp
  - source temp/bin/activate
  - asciidoc --backend install deckjs-1.6.2.zip
  - deactivate
script: make
