sudo: required
dist: trusty
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -y inkscape dia asciidoc python3-pip libxslt1-dev zlib1g-dev
- wget -c https://github.com/downloads/houqp/asciidoc-deckjs/deckjs-1.6.2.zip
- sudo pip3 install -r requirements.txt
- asciidoc --backend install deckjs-1.6.2.zip
script: make
env:
  global:
  - secure: YqPYuORzvh8m29dXW9PXT7n3rSTyK9Xufe06sCY/kcr3BmUxU+yWT+71NHsjRofdhUqCGGi4u8Cge5etNpbsWD8EG0T9s6H/chPQqM81ZmAKRWr2dBm65n+sXsTFMdZytNGc2VL8voWXtc26QDan+4xI2eTeHUL9QhRIKXCoGStHaHgvuwdNgTj9A/uk84Q0CCV1gXylNHFGdQ3C1gviguB79VRVNDzXXIOE4nJUloHYX1/JVhiSgErpb6jaxSOj1g2ThkLPI2iWlXkTSQpKn4tZ1BVuuDAzhPTeRGdurFF9PE4ORksOVXdOsbfbzhNKCR5P2Ydm8EST8YB82Vt28Rw2kDjTs4FrK6rqEocBTAsSz27zb3vSwkXVv3HodgzWWkyABuDBHE2PV7WRHP71nq/FvzEFzqNNSmxsT5Yu9k+xa07AmwW1BFGtU6bumgicFiwJI6KILB/3kIBOnfFyx+KdsuNis6RyY5S5ovjD6Z9bhkmQDi321VwTxAmNGlbrU4dGOZwYEBerMj3w4Y5JRZ3iFymkMZlr5oiQ4gDbla+1+ApPoN8INYKQ0lYv8NPpu1i+mM7H1pjjC71HAzQFkwukxXJC6GdJvkFqexIflVhmvMTo9+xqLxT8+I09LDLNJBf5rNiuIY/dTbz8PeuA1eiTtfxWdDQ+ptSzL31Tn2w=
after_success:
- bash deploy.sh
